[[pages]]
path = "s3_cost_sim/Home.py"
name = "Home: S3 Cost Deep Dive"
icon = "ğŸª£"

[[pages]]
path = "s3_cost_sim/pages/basics.py"
name = "Basics: S3 Cost Dimensions"
icon = "ğŸ“Š"

[[pages]]
name = "Scenario #1: Backup to Cloud"
icon = "â˜ï¸"
is_section = true

[[pages]]
path = "s3_cost_sim/pages/backup_to_cloud/home.py"
name = "Introduction"
icon = "1ï¸âƒ£"
in_section = true

[[pages]]
path = "s3_cost_sim/pages/backup_to_cloud/configuration.py"
name = "Backup Ingestion"
icon = "2ï¸âƒ£"
in_section = true

[[pages]]
name = "Scenario #2: Hybrid Environment"
icon = "ğŸ¢"
is_section = true

[[pages]]
path = "s3_cost_sim/pages/hybrid/home.py"
name = "Introduction"
icon = "1ï¸âƒ£"
in_section = true


[[pages]]
path = "s3_cost_sim/pages/hybrid/backup_archive.py"
name = "Backup & Archive"
icon = "2ï¸âƒ£"
in_section = true

[[pages]]
path = "s3_cost_sim/pages/hybrid/restore_retrieve.py"
name = "Restore & Retrieval"
icon = "3ï¸âƒ£"
in_section = true

[[pages]]
name = "Data Lake"
icon = ":ğŸŒŠ:"
is_section = true

[[pages]]
path = "s3_cost_sim/pages/data_lake/home.py"
name = "Introduction"
icon = "1ï¸âƒ£"
in_section = true

[[pages]]
path = "s3_cost_sim/pages/data_lake/known_access.py"
name = "Known Data Access Pattern"
icon = "2ï¸âƒ£"
in_section = true

[[pages]]
path = "s3_cost_sim/pages/data_lake/unknown_access.py"
name = "Unknown Data Access Pattern"
icon = "3ï¸âƒ£"
in_section = true

[[pages]]
name = "Special"
icon = "ğŸ‘¾"
is_section = true

[[pages]]
path = "s3_cost_sim/pages/special/home.py"
name = "Special Cases"
icon = "ğŸ‘½"
in_section = true
